# Generated by Django 3.2.25 on 2024-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_findings_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdetails_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('Kingdom', models.CharField(max_length=100)),
                ('Phylum', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('Order', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('Genus', models.CharField(max_length=100)),
                ('Species', models.CharField(max_length=100)),
                ('LifeCycle', models.CharField(max_length=300)),
            ],
        ),
    ]
