# Generated by Django 3.2.25 on 2024-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20241201_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdetails_table',
            old_name='Name',
            new_name='Common_Name',
        ),
        migrations.AddField(
            model_name='bdetails_table',
            name='Scientific_Name',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
    ]
