# Generated by Django 5.1.2 on 2024-12-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20241216_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdetails_table',
            name='LifeCycle',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='findings_table',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
