# Generated by Django 5.1.2 on 2024-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_bdetails_table_lifecycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findings_table',
            name='findings',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='findings_table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
