# Generated by Django 5.1.2 on 2024-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_findings_table_findings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findings_table',
            name='findings',
            field=models.TextField(max_length=50000),
        ),
    ]
